import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavbarTop from "./components/common/NavbarTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body>
        <NavbarTop />
          <div className="min-h-screen w-screen bg-slate-700">
            <div className="mx-auto min-h-screen w-11/12 py-5 px-5 bg-white shadow-2xl">
              <Providers>{children}</Providers>
            </div>
          </div>
      </body>
    </html>
  );
}
